### ISSUE TITLE
Breaking existing Prisma query types

### ISSUE THREAD

**Issue by gregg-cbs** [julienfdev/prisma-exclude-extension#2]
After using the extension I am now seeing this error:
![image](https://github.com/julienfdev/prisma-exclude-extension/assets/57114335/565268b2-6adb-4e14-8e85-1a554e3ab32b)

![image](https://github.com/julienfdev/prisma-exclude-extension/assets/57114335/3329fb1d-2319-4471-857f-8add0d006db8)

**Comment by julienfdev** [comment]
Wow, I'll take a look as soon as I can, this seems related to the extension API itself, not sure if it's my scope or Prisma's

**Comment by julienfdev** [comment]
Okay, pretty sure this is Prisma's type fallback : 

```
export const testExtension = Prisma.defineExtension((client) => client.$extends({}));
```

yields the same error, same thing if I don't extend the client and just return the extension object, so i'll close this issue because there's nothing I can do 😬

**Comment by gregg-cbs** [comment]
Damn :/ And i cant see a way to get around it either. Thanks
